# Generated by Django 4.2.2 on 2023-06-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_created_at_url_user_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='times_visited',
            field=models.IntegerField(default=0),
        ),
    ]
