# pull lightwight python image 
FROM python:3.9.17-alpine3.18

# set work directory
ENV APP_HOME=/usr/src/app
WORKDIR $APP_HOME

# create the app user
RUN addgroup -S app && adduser -S app -G app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#  upgrade pip && install dependencies 
RUN pip install --upgrade pip 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

